task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 2 # Set to your number of classes
remap_mscoco_category: False  # Must be False for custom datasets

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./data/yourdataset/images/train  # Relative path from project root
    ann_file: ./data/yourdataset/annotations/train.json  # Relative path from project root
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./data/yourdataset/images/val  # Relative path from project root
    ann_file: ./data/yourdataset/annotations/val.json  # Relative path from project root
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
